In [1]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt


import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

FileNotFoundError: [WinError 3] The system cannot find the path specified: '../input'

In [85]:
raindata = pd.read_csv("../input/rainfall-in-india/rainfall in india 1901-2015.csv")
print(raindata.head())

                 SUBDIVISION  YEAR   JAN   ...     Mar-May  Jun-Sep  Oct-Dec
0  ANDAMAN & NICOBAR ISLANDS  1901  49.2   ...       560.3   1696.3    980.3
1  ANDAMAN & NICOBAR ISLANDS  1902   0.0   ...       458.3   2185.9    716.7
2  ANDAMAN & NICOBAR ISLANDS  1903  12.7   ...       236.1   1874.0    690.6
3  ANDAMAN & NICOBAR ISLANDS  1904   9.4   ...       506.9   1977.6    571.0
4  ANDAMAN & NICOBAR ISLANDS  1905   1.3   ...       309.7   1624.9    630.8

[5 rows x 19 columns]

In [86]:
print(raindata.columns)
print(set(raindata['SUBDIVISION']))
# ap_rain= raindata[raindata['SUBDIVISION']=='Andhra Pradesh']
# print(set(raindata['Year']))
# ap_rain_2000 = ap_rain[ap_rain['Year'] == 2000]
# print(ap_rain_2000)

Index(['SUBDIVISION', 'YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb', 'Mar-May',
       'Jun-Sep', 'Oct-Dec'],
      dtype='object')
{'HARYANA DELHI & CHANDIGARH', 'CHHATTISGARH', 'UTTARAKHAND', 'COASTAL ANDHRA PRADESH', 'WEST MADHYA PRADESH', 'MADHYA MAHARASHTRA', 'ANDAMAN & NICOBAR ISLANDS', 'BIHAR', 'VIDARBHA', 'JAMMU & KASHMIR', 'ARUNACHAL PRADESH', 'NAGA MANI MIZO TRIPURA', 'SAURASHTRA & KUTCH', 'TELANGANA', 'SOUTH INTERIOR KARNATAKA', 'EAST RAJASTHAN', 'MATATHWADA', 'GUJARAT REGION', 'ORISSA', 'WEST RAJASTHAN', 'KONKAN & GOA', 'TAMIL NADU', 'EAST MADHYA PRADESH', 'GANGETIC WEST BENGAL', 'PUNJAB', 'WEST UTTAR PRADESH', 'NORTH INTERIOR KARNATAKA', 'LAKSHADWEEP', 'HIMACHAL PRADESH', 'KERALA', 'RAYALSEEMA', 'COASTAL KARNATAKA', 'EAST UTTAR PRADESH', 'JHARKHAND', 'ASSAM & MEGHALAYA', 'SUB HIMALAYAN WEST BENGAL & SIKKIM'}

In [87]:
valid_states_rain = raindata[(raindata['SUBDIVISION']=='BIHAR') | (raindata['SUBDIVISION']=='KERALA') | (raindata['SUBDIVISION']=='ARUNACHAL PRADESH')|(raindata['SUBDIVISION']=='TAMIL NADU')|(raindata['SUBDIVISION']=='JAMMU & KASHMIR')|(raindata['SUBDIVISION']=='UTTARAKHAND')|(raindata['SUBDIVISION']=='ORISSA')|(raindata['SUBDIVISION']=='HIMACHAL PRADESH')|(raindata['SUBDIVISION']=='LAKSHADWEEP')|(raindata['SUBDIVISION']=='PUNJAB')|(raindata['SUBDIVISION']=='CHHATTISGARH')|(raindata['SUBDIVISION']=='ANDAMAN & NICOBAR ISLANDS')|(raindata['SUBDIVISION']=='JHARKHAND')]

In [88]:
print(set(valid_states_rain['SUBDIVISION']))
print(valid_states_rain.head())
valid_states_rain = valid_states_rain[['SUBDIVISION','YEAR','ANNUAL']]
print(valid_states_rain.head())
print(valid_states_rain.describe())

{'TAMIL NADU', 'ANDAMAN & NICOBAR ISLANDS', 'BIHAR', 'JHARKHAND', 'JAMMU & KASHMIR', 'CHHATTISGARH', 'ARUNACHAL PRADESH', 'PUNJAB', 'LAKSHADWEEP', 'HIMACHAL PRADESH', 'KERALA', 'UTTARAKHAND', 'ORISSA'}
                 SUBDIVISION  YEAR   JAN   ...     Mar-May  Jun-Sep  Oct-Dec
0  ANDAMAN & NICOBAR ISLANDS  1901  49.2   ...       560.3   1696.3    980.3
1  ANDAMAN & NICOBAR ISLANDS  1902   0.0   ...       458.3   2185.9    716.7
2  ANDAMAN & NICOBAR ISLANDS  1903  12.7   ...       236.1   1874.0    690.6
3  ANDAMAN & NICOBAR ISLANDS  1904   9.4   ...       506.9   1977.6    571.0
4  ANDAMAN & NICOBAR ISLANDS  1905   1.3   ...       309.7   1624.9    630.8

[5 rows x 19 columns]
                 SUBDIVISION  YEAR  ANNUAL
0  ANDAMAN & NICOBAR ISLANDS  1901  3373.2
1  ANDAMAN & NICOBAR ISLANDS  1902  3520.7
2  ANDAMAN & NICOBAR ISLANDS  1903  2957.4
3  ANDAMAN & NICOBAR ISLANDS  1904  3079.6
4  ANDAMAN & NICOBAR ISLANDS  1905  2566.7
              YEAR       ANNUAL
count  1471.000000  1447.000000
mean   1958.611829  1623.911956
std      33.037181   881.150476
min    1901.000000   274.700000
25%    1930.000000  1087.500000
50%    1959.000000  1369.600000
75%    1987.000000  1781.850000
max    2015.000000  6331.100000

In [89]:
valid_states_rain = valid_states_rain[valid_states_rain['YEAR']>1996]

In [90]:
valid_states_rain.columns = ['State','Year','Rainfall']

In [91]:
valid_states_rain

                          State  Year  Rainfall
91    ANDAMAN & NICOBAR ISLANDS  1997    2755.1
92    ANDAMAN & NICOBAR ISLANDS  1998    2846.4
93    ANDAMAN & NICOBAR ISLANDS  1999    2699.7
94    ANDAMAN & NICOBAR ISLANDS  2000    2763.2
95    ANDAMAN & NICOBAR ISLANDS  2001    3080.9
96    ANDAMAN & NICOBAR ISLANDS  2002    2620.2
97    ANDAMAN & NICOBAR ISLANDS  2003    2355.9
98    ANDAMAN & NICOBAR ISLANDS  2004    2460.1
99    ANDAMAN & NICOBAR ISLANDS  2005    2954.7
100   ANDAMAN & NICOBAR ISLANDS  2006    2404.7
101   ANDAMAN & NICOBAR ISLANDS  2007    2748.0
102   ANDAMAN & NICOBAR ISLANDS  2008    3374.8
103   ANDAMAN & NICOBAR ISLANDS  2009    2538.6
104   ANDAMAN & NICOBAR ISLANDS  2010    3157.1
105   ANDAMAN & NICOBAR ISLANDS  2011    3828.0
106   ANDAMAN & NICOBAR ISLANDS  2012    3497.6
107   ANDAMAN & NICOBAR ISLANDS  2013    3757.8
108   ANDAMAN & NICOBAR ISLANDS  2014    2622.4
109   ANDAMAN & NICOBAR ISLANDS  2015    2904.6
188           ARUNACHAL PRADESH  1997    2274.9
189           ARUNACHAL PRADESH  1998    3616.7
190           ARUNACHAL PRADESH  1999    2316.6
191           ARUNACHAL PRADESH  2000    2596.8
192           ARUNACHAL PRADESH  2001    2036.0
193           ARUNACHAL PRADESH  2002    2389.2
194           ARUNACHAL PRADESH  2003    2451.8
195           ARUNACHAL PRADESH  2004    2545.7
196           ARUNACHAL PRADESH  2005    2335.5
197           ARUNACHAL PRADESH  2006    2259.6
198           ARUNACHAL PRADESH  2007    3020.7
...                         ...   ...       ...
3991                     KERALA  2005    3031.1
3992                     KERALA  2006    3420.6
3993                     KERALA  2007    3489.6
3994                     KERALA  2008    2524.5
3995                     KERALA  2009    2810.6
3996                     KERALA  2010    3131.8
3997                     KERALA  2011    3035.1
3998                     KERALA  2012    2151.1
3999                     KERALA  2013    3255.4
4000                     KERALA  2014    3046.4
4001                     KERALA  2015    2600.6
4097                LAKSHADWEEP  1997    1764.7
4098                LAKSHADWEEP  1998    1986.9
4099                LAKSHADWEEP  1999    1857.3
4100                LAKSHADWEEP  2000    1372.1
4101                LAKSHADWEEP  2001    1380.6
4102                LAKSHADWEEP  2002    1033.5
4103                LAKSHADWEEP  2003    1532.9
4104                LAKSHADWEEP  2004    1553.2
4105                LAKSHADWEEP  2005    1575.4
4106                LAKSHADWEEP  2006    1598.6
4107                LAKSHADWEEP  2007    2361.6
4108                LAKSHADWEEP  2008    1726.8
4109                LAKSHADWEEP  2009    1570.1
4110                LAKSHADWEEP  2010    1725.2
4111                LAKSHADWEEP  2011    1533.7
4112                LAKSHADWEEP  2012    1405.5
4113                LAKSHADWEEP  2013    1426.3
4114                LAKSHADWEEP  2014    1395.0
4115                LAKSHADWEEP  2015    1642.9

[247 rows x 3 columns]

In [92]:
cropdata = pd.read_csv("../input/crop-data/apy.csv")
cropdata.head()

                    State_Name District_Name    ...        Area Production
0  Andaman and Nicobar Islands      NICOBARS    ...      1254.0     2000.0
1  Andaman and Nicobar Islands      NICOBARS    ...         2.0        1.0
2  Andaman and Nicobar Islands      NICOBARS    ...       102.0      321.0
3  Andaman and Nicobar Islands      NICOBARS    ...       176.0      641.0
4  Andaman and Nicobar Islands      NICOBARS    ...       720.0      165.0

[5 rows x 7 columns]

In [93]:
print(cropdata.columns)
print(set(cropdata['State_Name']))

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area',
       'Production'],
      dtype='object')
{'Uttar Pradesh', 'Chhattisgarh', 'Tripura', 'Uttarakhand', 'Mizoram', 'Andaman and Nicobar Islands', 'Kerala', 'Manipur', 'Andhra Pradesh', 'Assam', 'Rajasthan', 'Jharkhand', 'West Bengal', 'Goa', 'Punjab', 'Maharashtra', 'Arunachal Pradesh', 'Jammu and Kashmir ', 'Tamil Nadu', 'Chandigarh', 'Meghalaya', 'Sikkim', 'Himachal Pradesh', 'Puducherry', 'Bihar', 'Nagaland', 'Madhya Pradesh', 'Odisha', 'Telangana ', 'Gujarat', 'Dadra and Nagar Haveli', 'Karnataka', 'Haryana'}

In [94]:
valid_states_crop = cropdata[(cropdata['State_Name']=='Bihar') | (cropdata['State_Name']=='Kerala') | (cropdata['State_Name']=='Arunachal Pradesh')|(cropdata['State_Name']=='Tamil Nadu')|(cropdata['State_Name']=='Jammu and Kashmir ')|(cropdata['State_Name']=='Uttarakhand')|(cropdata['State_Name']=='Odisha')|(cropdata['State_Name']=='Himachal Pradesh')|(cropdata['State_Name']=='Punjab')|(cropdata['State_Name']=='Chhattisgarh')|(cropdata['State_Name']=='Jharkhand')]

In [95]:
print(set(valid_states_crop['State_Name']))
print(set(valid_states_rain['State']))

{'Chhattisgarh', 'Uttarakhand', 'Odisha', 'Jharkhand', 'Himachal Pradesh', 'Kerala', 'Punjab', 'Arunachal Pradesh', 'Jammu and Kashmir ', 'Bihar', 'Tamil Nadu'}
{'TAMIL NADU', 'ANDAMAN & NICOBAR ISLANDS', 'BIHAR', 'JHARKHAND', 'JAMMU & KASHMIR', 'CHHATTISGARH', 'ARUNACHAL PRADESH', 'PUNJAB', 'LAKSHADWEEP', 'HIMACHAL PRADESH', 'KERALA', 'UTTARAKHAND', 'ORISSA'}

In [96]:
valid_states_rain = valid_states_rain[valid_states_rain.State != 'LAKSHADWEEP']
valid_states_crop = valid_states_crop.replace('Jammu and Kashmir ','Jammu and Kashmir')
valid_states_rain = valid_states_rain.replace('UTTARAKHAND','Uttarakhand')
valid_states_rain = valid_states_rain.replace('ORISSA','Odisha')
valid_states_rain = valid_states_rain.replace('HIMACHAL PRADESH','Himachal Pradesh')
valid_states_rain = valid_states_rain.replace('JHARKHAND','Jharkhand')
valid_states_rain = valid_states_rain.replace('ARUNACHAL PRADESH','Arunachal Pradesh')
valid_states_rain = valid_states_rain.replace('TAMIL NADU','Tamil Nadu')
valid_states_rain = valid_states_rain.replace('CHHATTISGARH','Chhattisgarh')
valid_states_rain = valid_states_rain.replace('JAMMU & KASHMIR','Jammu and Kashmir')
valid_states_rain = valid_states_rain.replace('ANDAMAN & NICOBAR ISLANDS','Andaman and Nicobar Islands')
valid_states_rain = valid_states_rain.replace('BIHAR','Bihar')
valid_states_rain = valid_states_rain.replace('PUNJAB','Punjab')
valid_states_rain = valid_states_rain.replace('KERALA','Kerala')

In [97]:
print(set(valid_states_crop['State_Name']))
print(set(valid_states_rain['State']))

{'Chhattisgarh', 'Uttarakhand', 'Odisha', 'Jharkhand', 'Himachal Pradesh', 'Kerala', 'Jammu and Kashmir', 'Arunachal Pradesh', 'Punjab', 'Bihar', 'Tamil Nadu'}
{'Chhattisgarh', 'Uttarakhand', 'Odisha', 'Andaman and Nicobar Islands', 'Jharkhand', 'Punjab', 'Himachal Pradesh', 'Jammu and Kashmir', 'Arunachal Pradesh', 'Kerala', 'Bihar', 'Tamil Nadu'}

In [100]:
#valid_states_crop.columns = ['State','Year','Crop','Area','Production','Rainfall']
Rainfall_list = [0]*76986
valid_states_crop['Rainfall'] = Rainfall_list
#valid_states_crop.shape

In [101]:
print(valid_states_crop.head())
print(valid_states_rain.head())

             State_Name District_Name   ...     Production Rainfall
9831  Arunachal Pradesh         ANJAW   ...         2674.0        0
9832  Arunachal Pradesh         ANJAW   ...         1914.0        0
9833  Arunachal Pradesh         ANJAW   ...          495.0        0
9834  Arunachal Pradesh         ANJAW   ...           60.0        0
9835  Arunachal Pradesh         ANJAW   ...           18.0        0

[5 rows x 8 columns]
                          State  Year  Rainfall
91  Andaman and Nicobar Islands  1997    2755.1
92  Andaman and Nicobar Islands  1998    2846.4
93  Andaman and Nicobar Islands  1999    2699.7
94  Andaman and Nicobar Islands  2000    2763.2
95  Andaman and Nicobar Islands  2001    3080.9

In [103]:
states_set = set(valid_states_crop['State_Name'])
year_set = set(valid_states_crop['Crop_Year'])
print(states_set)
print(year_set)

{'Chhattisgarh', 'Uttarakhand', 'Odisha', 'Jharkhand', 'Himachal Pradesh', 'Kerala', 'Jammu and Kashmir', 'Arunachal Pradesh', 'Punjab', 'Bihar', 'Tamil Nadu'}
{1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015}

In [104]:
for state in states_set:
    for year in year_set:
        #print(valid_states_crop[valid_states_crop['State']==state]['Year'])
        if(year in list(valid_states_crop[valid_states_crop['State_Name']==state]['Crop_Year'])):
            #print(state,year)
            valid_states_crop.loc[(valid_states_crop['State_Name']==state) & \
                              (valid_states_crop['Crop_Year']==year),'Rainfall']= \
            list(valid_states_rain[(valid_states_rain['State']==state) & \
                                   (valid_states_rain['Year']==year)]['Rainfall'])[0]

In [105]:
valid_states_crop

               State_Name District_Name   ...     Production Rainfall
9831    Arunachal Pradesh         ANJAW   ...         2674.0   2545.7
9832    Arunachal Pradesh         ANJAW   ...         1914.0   2545.7
9833    Arunachal Pradesh         ANJAW   ...          495.0   2545.7
9834    Arunachal Pradesh         ANJAW   ...           60.0   2545.7
9835    Arunachal Pradesh         ANJAW   ...           18.0   2545.7
9836    Arunachal Pradesh         ANJAW   ...          420.0   2545.7
9837    Arunachal Pradesh         ANJAW   ...          688.0   2545.7
9838    Arunachal Pradesh         ANJAW   ...           50.0   2545.7
9839    Arunachal Pradesh         ANJAW   ...           20.0   2545.7
9840    Arunachal Pradesh         ANJAW   ...         2700.0   2335.5
9841    Arunachal Pradesh         ANJAW   ...         5000.0   2335.5
9842    Arunachal Pradesh         ANJAW   ...          525.0   2335.5
9843    Arunachal Pradesh         ANJAW   ...           65.0   2335.5
9844    Arunachal Pradesh         ANJAW   ...           28.0   2335.5
9845    Arunachal Pradesh         ANJAW   ...          455.0   2335.5
9846    Arunachal Pradesh         ANJAW   ...          720.0   2335.5
9847    Arunachal Pradesh         ANJAW   ...           70.0   2335.5
9848    Arunachal Pradesh         ANJAW   ...           25.0   2335.5
9849    Arunachal Pradesh         ANJAW   ...         3719.0   2259.6
9850    Arunachal Pradesh         ANJAW   ...         3004.0   2259.6
9851    Arunachal Pradesh         ANJAW   ...          492.0   2259.6
9852    Arunachal Pradesh         ANJAW   ...           73.0   2259.6
9853    Arunachal Pradesh         ANJAW   ...           30.0   2259.6
9854    Arunachal Pradesh         ANJAW   ...         1199.0   2259.6
9855    Arunachal Pradesh         ANJAW   ...           75.0   2259.6
9856    Arunachal Pradesh         ANJAW   ...          925.0   2259.6
9857    Arunachal Pradesh         ANJAW   ...            7.0   2259.6
9858    Arunachal Pradesh         ANJAW   ...           76.0   2259.6
9859    Arunachal Pradesh         ANJAW   ...         3763.0   3020.7
9860    Arunachal Pradesh         ANJAW   ...         2530.0   3020.7
...                   ...           ...   ...            ...      ...
236448        Uttarakhand   UTTAR KASHI   ...          151.0   1287.4
236449        Uttarakhand   UTTAR KASHI   ...         1763.0   1287.4
236450        Uttarakhand   UTTAR KASHI   ...            1.0   1287.4
236451        Uttarakhand   UTTAR KASHI   ...        17751.0   1287.4
236452        Uttarakhand   UTTAR KASHI   ...         3886.0   1287.4
236453        Uttarakhand   UTTAR KASHI   ...         9233.0   1287.4
236454        Uttarakhand   UTTAR KASHI   ...        16499.0   1287.4
236455        Uttarakhand   UTTAR KASHI   ...          157.0   1287.4
236456        Uttarakhand   UTTAR KASHI   ...         4498.0   1287.4
236457        Uttarakhand   UTTAR KASHI   ...          169.0   1287.4
236458        Uttarakhand   UTTAR KASHI   ...        35035.0   1287.4
236459        Uttarakhand   UTTAR KASHI   ...          680.0   1287.4
236460        Uttarakhand   UTTAR KASHI   ...          272.0   1287.4
236461        Uttarakhand   UTTAR KASHI   ...            2.0   1287.4
236462        Uttarakhand   UTTAR KASHI   ...          236.0   1287.4
236463        Uttarakhand   UTTAR KASHI   ...          236.0   1287.4
236464        Uttarakhand   UTTAR KASHI   ...            2.0   1287.4
236465        Uttarakhand   UTTAR KASHI   ...          499.0   1287.4
236466        Uttarakhand   UTTAR KASHI   ...         1785.0   1287.4
236467        Uttarakhand   UTTAR KASHI   ...          744.0   1287.4
236468        Uttarakhand   UTTAR KASHI   ...          742.0   1287.4
236469        Uttarakhand   UTTAR KASHI   ...        14654.0   1287.4
236470        Uttarakhand   UTTAR KASHI   ...        13643.0   1287.4
236471        Uttarakhand   UTTAR KASHI   ...           43.0   1287.4
236472        Uttarakhand   UTTAR KASHI   ...           18.0   1287.4
236473        Uttarakhand   UTTAR KASHI   ...          172.0   1287.4
236474        Uttarakhand   UTTAR KASHI   ...         4630.0   1287.4
236475        Uttarakhand   UTTAR KASHI   ...        16499.0   1287.4
236476        Uttarakhand   UTTAR KASHI   ...            3.0   1287.4
236477        Uttarakhand   UTTAR KASHI   ...        49689.0   1287.4

[76986 rows x 8 columns]

In [107]:
crop_data_alpha = valid_states_crop.dropna()
crop_data_alpha = crop_data_alpha[crop_data_alpha.Production !=0.0]
print(crop_data_alpha.head())
print(set(crop_data_alpha['Crop']))
crop_data_alpha.shape

             State_Name District_Name   ...     Production Rainfall
9831  Arunachal Pradesh         ANJAW   ...         2674.0   2545.7
9832  Arunachal Pradesh         ANJAW   ...         1914.0   2545.7
9833  Arunachal Pradesh         ANJAW   ...          495.0   2545.7
9834  Arunachal Pradesh         ANJAW   ...           60.0   2545.7
9835  Arunachal Pradesh         ANJAW   ...           18.0   2545.7

[5 rows x 8 columns]
{'Urad', 'other oilseeds', 'Maize', 'Arecanut', 'Cond-spcs other', 'Khesari', 'Blackgram', 'Coffee', 'Other Kharif pulses', 'Tomato', 'Paddy', 'Cashewnut', 'Turnip', 'Beans & Mutter(Vegetable)', 'Potato', 'Oilseeds total', 'Other Vegetables', 'Total foodgrain', 'Cotton(lint)', 'Pome Fruit', 'Ragi', 'Barley', 'Tobacco', 'Orange', 'Gram', 'Garlic', 'Sunflower', 'Peas & beans (Pulses)', 'Drum Stick', 'Jack Fruit', 'Bhindi', 'Rapeseed &Mustard', 'Brinjal', 'Redish', 'Cardamom', 'Guar seed', 'Masoor', 'Pineapple', 'Varagu', 'Sannhamp', 'Arhar/Tur', 'Horse-gram', 'Cabbage', 'Small millets', 'Papaya', 'Sweet potato', 'Coriander', 'Dry ginger', 'Soyabean', 'Lentil', 'Sesamum', 'Turmeric', 'Moth', 'Cashewnut Raw', 'Niger seed', 'Citrus Fruit', 'Banana', 'Ginger', 'Samai', 'Black pepper', 'Castor seed', 'other misc. pulses', 'Safflower', 'Groundnut', 'Onion', 'Jowar', 'Tea', 'Other Cereals & Millets', 'Mesta', 'Korra', 'Coconut ', 'Sugarcane', 'Linseed', 'Mango', 'Dry chillies', 'Wheat', 'Grapes', 'Jute', 'Bajra', 'Pulses total', 'Rubber', 'Tapioca', 'Carrot', 'Moong(Green Gram)', 'Rice', 'Other  Rabi pulses'}

(74774, 8)

In [ ]:
crop_data_alpha = crop_data_alpha.drop('State_Name',axis = 1)
crop_data_alpha = crop_data_alpha.drop('Season',axis = 1)
crop_data_alpha = crop_data_alpha.drop('Crop_Year',axis = 1)
crop_data_alpha = crop_data_alpha.sort_values(by='Crop')
crop_data_alpha = crop_data_alpha.reset_index(drop=True)
print(crop_data_alpha.head())

In [ ]:
for index,row in crop_data_alpha.iterrows():
    crop_data_alpha.loc[index,'Production'] = row['Production']/row['Area']
crop_data_alpha.head()

In [ ]:
wheat_data = crop_data_alpha[crop_data_alpha['Crop']=='Wheat']
print(len(wheat_data))
print(wheat_data.head())
print(wheat_data[wheat_data['Production']==3.0])

In [ ]:
plt.scatter(wheat_data['Production'],wheat_data['Rainfall'])

In [ ]:
potato_data = crop_data_alpha[crop_data_alpha['Crop']=='Potato']
plt.scatter(potato_data['Production'],potato_data['Rainfall'])